global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
  - job_name: "otel-metrics"
    static_configs:
      - targets: ["otel-collector:9464"]
